import Head from 'next/head';

export default function Header()
{
	return(
		<Head>
			<title>Next App</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
			<script async src={`https://www.googletagmanager.com/gtag/js?id=G-6T0S3MCKXJ`}></script>
			<script
			dangerouslySetInnerHTML={{
				__html:`
					window.dataLayer = window.dataLayer || [];
					function gtag(){dataLayer.push(arguments);}
					gtag('js', new Date());
					gtag('config', G-6T0S3MCKXJ);
				`
			}}>
			</script>
		</Head>
	);
};
